version: '3.2'
services:
  php-fpm:
    build: './php/'
    container_name: php-fpm
    networks:
      - backend
    working_dir: /var/www/html/
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.3
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=1a
      - MYSQL_DATABASE=calendar
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1a
      - TZ=Asia/Bangkok
    ports:
      - "8989:3306"
    volumes:
      - "./mariaDB/data:/var/lib/mysql"
    networks:
      - backend
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8181:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    restart: always
    depends_on:
      - mariadb
    networks:
      - backend
  nginx:
    build: './nginx/'
    container_name: nginx
    depends_on:
      - php-fpm
      - mariadb
    working_dir: /var/www/html/
    volumes:
      - ./src:/var/www/html/
    ports:
      - "81:80"
      - "4443:443"
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend: